{{- if .Values.btc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind-deployment
  namespace: shkeeper
  labels:
    app: bitcoind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:

      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/templates/default.conf.template
          subPath: default.conf.template
        - mountPath: /backup
          name: backup
        env:
        - name: SHKEEPER_BACKEND_KEY
          valueFrom:
            secretKeyRef:
              name: shkeeper-btc-key
              key: password


      - name: bitcoind
        image: lncm/bitcoind
        env:
          - name: BTC_USERNAME
            valueFrom:
              secretKeyRef:
                name: bitcoin-rpc
                key: username
                optional: false
          - name: BTC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bitcoin-rpc
                key: password
                optional: false
          - name: SHKEEPER_BACKEND_KEY
            valueFrom:
              secretKeyRef:
                name: shkeeper-btc-key
                key: password
                optional: false
        volumeMounts:
        - name: bitcoind-storage
          mountPath: /root/.bitcoin
        - name: backup
          mountPath: /backup
      volumes:
      - name: bitcoind-storage
        persistentVolumeClaim:
          claimName: bitcoind-claim
      - name: backup
        emptyDir:
          medium: Memory
      - name: nginx-config
        configMap:
          name: nginx-config
{{- end }}
